CREATE TABLE usuario (
	email VARCHAR(100),
	username VARCHAR(100) NOT NULL,
	senha VARCHAR(100) NOT NULL,
	url TEXT NOT NULL,
	cor VARCHAR(10),
	PRIMARY KEY (email)
)ENGINE = InnoDB;
CREATE TABLE bebe(
	nickname VARCHAR(100), 
	nome VARCHAR(100) NOT NULL,
	nascimento DATE NOT NULL,
	sexo VARCHAR(10) NOT NULL,
	url TEXT,
	PRIMARY KEY(nickname)
)ENGINE = InnoDB;
CREATE TABLE album(
	nicknameBebe VARCHAR(100) NOT NULL, 
	nome VARCHAR(100),
	FOREIGN KEY(nicknameBebe) REFERENCES bebe(nickname) ON UPDATE CASCADE ON DELETE CASCADE,
 	PRIMARY KEY(nicknameBebe, nome)
)ENGINE = InnoDB;
CREATE TABLE foto(
	id SERIAL,
	nicknameBebe VARCHAR(100), 
	nomeAlbum VARCHAR(100),
	url TEXT NOT NULL,
	CONSTRAINT FotoFK1 FOREIGN KEY(nicknameBebe) REFERENCES bebe(nickname) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FotoFK2 FOREIGN KEY(nomeAlbum) REFERENCES album(nome) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(id)
)ENGINE = InnoDB;
CREATE TABLE recado (
	id SERIAL,
	nicknameBebe VARCHAR (100) NOT NULL,
	data DATE NOT NULL,
	hora TIME NOT NULL,
	mensagem TEXT NOT NULL,
	FOREIGN KEY (nicknameBebe) REFERENCES bebe(nickname) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (id)
)ENGINE = InnoDB;
CREATE TABLE evento (
	id SERIAL,
	nicknameBebe VARCHAR(100) NOT NULL,
	data DATE NOT NULL,
	descricao TEXT NOT NULL,
	FOREIGN KEY (nicknameBebe) REFERENCES bebe(nickname) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (id)
)ENGINE = InnoDB;
CREATE TABLE produto (
	id SERIAL,
	nicknameBebe VARCHAR(100) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (nicknameBebe) REFERENCES bebe(nickname) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (id)
)ENGINE = InnoDB;
CREATE TABLE usuarioTemBebe (
	email VARCHAR(100),
	nicknameBebe VARCHAR(100),
	FOREIGN KEY (email) REFERENCES usuario(email) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (nicknameBebe) REFERENCES bebe(nickname) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (email, nicknameBebe)
)ENGINE = InnoDB;